#!/bin/sh

CACHE_FILE=/tmp/$$.pid

# Check for eslint
which eslint &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "\t\033[41mPlease install ESlint\033[0m"
  exit 1
fi

# Clear our cache file
rm $CACHE_FILE 2>/dev/null
for FILE in $(find . -name '*.js')
do
  (
    eslint "$FILE"
    if [[ "$?" != 0 ]]; then
      echo -n "$FILE ">>$CACHE_FILE
    fi
  ) &
done
wait

ALL_PASSED=true
if [ -f $CACHE_FILE ]; then
  ALL_PASSED=false
fi

if ! $ALL_PASSED; then
  echo "FILES $(cat $CACHE_FILE)"
  $EDITOR $(cat $CACHE_FILE)
  exit 1
fi

exit $?
