"use strict";

// Usage: node domain.js <string>
//
// Or go wild:
//   node domain.js shortlink|head -n 600|tail -n 100|tee /dev/tty|c

// XXX: wordhippo.com is useful

const removeOneChar = string => {
  const out = [string];
  for (let i = 0; i < string.length; i++) {
    out.push(
      string
        .split("")
        .filter((a, index, c) => {
          return index !== i;
        })
        .join("")
    );
  }
  return out;
};

// (function(string) {
//   console.log(
//     removeOneChar(string)
//       .flatMap(removeOneChar)
//       .flatMap(removeOneChar)
//       .flatMap(removeOneChar)
//       .flatMap(removeOneChar)
//       .filter(x => x.length === 5)
//     // .filter(x => x.match(/^s.*lnk$/))
//       .join('.com\n') + '.com',
//   );
// })(process.argv[2]);

// const IMPROVE = [
//   'improve',
//   'advance',
//   'boost',
//   'lift',
//   'revamp',
//   'rise',
//   'upgrade',
//   'soar',
//   'rocket',
// ];

const MOBILE = [
  ...new Set([
    "do",
    "go",
    "act",
    "age",
    "aim",
    "bag",
    "bar",
    "bed",
    "bit",
    "biz",
    "cut",
    "end",
    "fit",
    "gap",
    "gig",
    "hui",
    "job",
    "joe",
    "lay",
    "lot",
    "min",
    "mob",
    "now",
    "par",
    "pay",
    "peg",
    "row",
    "sec",
    "set",
    "tad",
    "tea",
    "use",
    "vow",
    "way",
    "wee",
    "zone",
    "area",
    "arts",
    "band",
    "beat",
    "beds",
    "bite",
    "body",
    "bond",
    "brew",
    "byte",
    "cafe",
    "call",
    "care",
    "case",
    "chat",
    "coup",
    "crew",
    "date",
    "deal",
    "deed",
    "desk",
    "dole",
    "dose",
    "drip",
    "duty",
    "eats",
    "edge",
    "fame",
    "fate",
    "fief",
    "file",
    "folk",
    "form",
    "gain",
    "gale",
    "game",
    "gang",
    "gear",
    "gems",
    "goal",
    "grip",
    "gush",
    "gust",
    "hand",
    "hang",
    "herd",
    "hire",
    "home",
    "inch",
    "jazz",
    "jiff",
    "keep",
    "kind",
    "knot",
    "lick",
    "life",
    "line",
    "luck",
    "mana",
    "mark",
    "mass",
    "meet",
    "mode",
    "name",
    "next",
    "nick",
    "note",
    "oath",
    "onus",
    "pack",
    "pact",
    "part",
    "pill",
    "plan",
    "play",
    "post",
    "race",
    "rank",
    "rate",
    "rise",
    "rite",
    "role",
    "rule",
    "rung",
    "rush",
    "sale",
    "salt",
    "show",
    "size",
    "slot",
    "snap",
    "sofa",
    "sort",
    "spot",
    "stab",
    "stay",
    "step",
    "stop",
    "talk",
    "task",
    "term",
    "tick",
    "tier",
    "time",
    "trim",
    "turf",
    "type",
    "unit",
    "walk",
    "wave",
    "wink",
    "word",
    "work",
    "writ",
    "annex",
    "arena",
    "award",
    "basis",
    "beads",
    "being",
    "berth",
    "birth",
    "blaze",
    "bling",
    "blink",
    "blood",
    "boost",
    "brand",
    "break",
    "brief",
    "brush",
    "bunch",
    "burst",
    "caste",
    "chair",
    "chest",
    "chore",
    "class",
    "clout",
    "couch",
    "crack",
    "craft",
    "crowd",
    "crush",
    "debut",
    "decor",
    "décor",
    "dodge",
    "draft",
    "drove",
    "event",
    "extra",
    "facts",
    "favor",
    "field",
    "flare",
    "flash",
    "flock",
    "forte",
    "forum",
    "front",
    "funds",
    "gears",
    "genus",
    "goods",
    "grade",
    "grant",
    "grind",
    "group",
    "honor",
    "horde",
    "house",
    "hutch",
    "image",
    "issue",
    "izzat",
    "jiffy",
    "kudos",
    "labor",
    "lease",
    "level",
    "means",
    "merit",
    "niche",
    "notch",
    "orbit",
    "order",
    "panel",
    "paper",
    "party",
    "phase",
    "piece",
    "place",
    "plane",
    "point",
    "power",
    "proxy",
    "purge",
    "quest",
    "queue",
    "quick",
    "quite",
    "quota",
    "raise",
    "rally",
    "ranks",
    "reach",
    "realm",
    "scene",
    "scoop",
    "score",
    "setup",
    "shade",
    "shake",
    "shape",
    "share",
    "shift",
    "sitch",
    "skill",
    "snack",
    "spasm",
    "spell",
    "sport",
    "stage",
    "start",
    "state",
    "stint",
    "stock",
    "stool",
    "storm",
    "story",
    "stuff",
    "surge",
    "swarm",
    "synod",
    "table",
    "terms",
    "thing",
    "times",
    "title",
    "touch",
    "trade",
    "tribe",
    "trice",
    "trims",
    "truce",
    "trust",
    "tryst",
    "union",
    "units",
    "value",
    "varna",
    "visit",
    "while",
    "world",
    "worth",
    "accord",
    "action",
    "add-on",
    "affair",
    "agency",
    "annexe",
    "a rise",
    "ascent",
    "asking",
    "assent",
    "avowal",
    "barony",
    "billet",
    "binder",
    "breath",
    "brevet",
    "bubble",
    "buffet",
    "burden",
    "bureau",
    "buying",
    "cachet",
    "career",
    "cartel",
    "caucus",
    "chairs",
    "change",
    "charge",
    "choice",
    "circle",
    "confab",
    "credit",
    "crisis",
    "custom",
    "debate",
    "decree",
    "degree",
    "design",
    "detail",
    "device",
    "devoir",
    "dialog",
    "dicker",
    "domain",
    "effect",
    "effort",
    "employ",
    "envoys",
    "errand",
    "estate",
    "esteem",
    "extras",
    "family",
    "favour",
    "fettle",
    "finery",
    "fixing",
    "frills",
    "gentry",
    "giving",
    "groove",
    "growth",
    "health",
    "height",
    "hiring",
    "honors",
    "honour",
    "huddle",
    "income",
    "intent",
    "jewels",
    "kilter",
    "labour",
    "launch",
    "league",
    "legacy",
    "leg-up",
    "livery",
    "living",
    "matter",
    "meetup",
    "metier",
    "métier",
    "metric",
    "minute",
    "moment",
    "muster",
    "naming",
    "nature",
    "nuance",
    "object",
    "office",
    "option",
    "origin",
    "outfit",
    "papers",
    "parley",
    "payoff",
    "period",
    "permit",
    "pigeon",
    "pledge",
    "plight",
    "powwow",
    "prides",
    "pronto",
    "racket",
    "rating",
    "ration",
    "record",
    "regard",
    "remove",
    "renown",
    "repair",
    "report",
    "repute",
    "result",
    "ritual",
    "rubric",
    "ruling",
    "scheme",
    "second",
    "sector",
    "set up",
    "set-up",
    "sit-in",
    "sphere",
    "splash",
    "status",
    "stirps",
    "strain",
    "string",
    "stuffs",
    "summit",
    "supply",
    "surety",
    "system",
    "tables",
    "target",
    "tenure",
    "things",
    "throng",
    "treaty",
    "upkeep",
    "vacuum",
    "virtue",
    "voting",
    "weight",
    "account",
    "adapter",
    "adaptor",
    "adjunct",
    "advance",
    "affairs",
    "annuity",
    "apparel",
    "awayday",
    "baggage",
    "balance",
    "baptism",
    "bargain",
    "baubles",
    "booking",
    "bracket",
    "cabinet",
    "caliber",
    "calibre",
    "calling",
    "chapter",
    "charter",
    "chattel",
    "climate",
    "cluster",
    "codicil",
    "command",
    "commode",
    "compact",
    "company",
    "concern",
    "concord",
    "consent",
    "consult",
    "contact",
    "context",
    "council",
    "counsel",
    "counter",
    "culling",
    "day gig",
    "day job",
    "dealing",
    "demesne",
    "descent",
    "designs",
    "destiny",
    "details",
    "dignity",
    "dilemma",
    "diploma",
    "doodads",
    "draught",
    "dresser",
    "dunking",
    "echelon",
    "effects",
    "element",
    "embassy",
    "entente",
    "evening",
    "faction",
    "faculty",
    "feature",
    "fiefdom",
    "finding",
    "fitment",
    "fitting",
    "fixture",
    "flosses",
    "flowers",
    "footing",
    "fortune",
    "gabfest",
    "gewgaws",
    "grading",
    "harmony",
    "hearing",
    "highboy",
    "holiday",
    "honours",
    "instant",
    "issuing",
    "keeping",
    "kingdom",
    "laurels",
    "legates",
    "licence",
    "license",
    "lineage",
    "look-in",
    "mandate",
    "matinee",
    "meaning",
    "measure",
    "meeting",
    "mission",
    "move up",
    "nominee",
    "no time",
    "opening",
    "origins",
    "outcome",
    "outlook",
    "palaver",
    "panoply",
    "picking",
    "picture",
    "placing",
    "portion",
    "posting",
    "posture",
    "primacy",
    "process",
    "program",
    "project",
    "promise",
    "purpose",
    "pursuit",
    "quality",
    "quickie",
    "quietus",
    "ranking",
    "rapport",
    "reaches",
    "regalia",
    "resolve",
    "results",
    "reunion",
    "rigging",
    "roundup",
    "runanga",
    "section",
    "selling",
    "seminar",
    "service",
    "serving",
    "session",
    "setoffs",
    "setting",
    "sharing",
    "signing",
    "society",
    "sojourn",
    "sorting",
    "species",
    "station",
    "stature",
    "step up",
    "stratum",
    "subsidy",
    "support",
    "swindle",
    "symbols",
    "terrain",
    "the nod",
    "turnout",
    "tweetup",
    "twinkle",
    "upgrade",
    "utility",
    "vacancy",
    "venture",
    "verdict",
    "warrant",
    "weekend",
    "ablution",
    "activity",
    "addition",
    "adoption",
    "alliance",
    "alloting",
    "analysis",
    "ancestry",
    "apparels",
    "approval",
    "argument",
    "assembly",
    "audience",
    "audition",
    "awarding",
    "baggages",
    "ballgame",
    "behavior",
    "bestowal",
    "bookcase",
    "breeding",
    "business",
    "cabinets",
    "capacity",
    "category",
    "catering",
    "ceremony",
    "chattels",
    "choosing",
    "clambake",
    "classing",
    "colloquy",
    "conclave",
    "congress",
    "contract",
    "costumes",
    "courtesy",
    "covenant",
    "creation",
    "crowning",
    "cupboard",
    "decision",
    "defining",
    "delegacy",
    "delegate",
    "delivery",
    "deputies",
    "dialogue",
    "dingbats",
    "dispatch",
    "disposal",
    "division",
    "document",
    "electing",
    "election",
    "eminence",
    "endeavor",
    "engaging",
    "entrance",
    "equipage",
    "eruption",
    "exchange",
    "exercise",
    "existing",
    "eyeblink",
    "festoons",
    "findings",
    "fineries",
    "fitments",
    "fittings",
    "fixtures",
    "flare-up",
    "flounces",
    "founding",
    "frame-up",
    "frippery",
    "function",
    "gildings",
    "granting",
    "grouping",
    "guaranty",
    "heritage",
    "homework",
    "industry",
    "instance",
    "interest",
    "issuance",
    "jamboree",
    "judgment",
    "junction",
    "juncture",
    "kindness",
    "labeling",
    "legation",
    "lifework",
    "liveries",
    "makeover",
    "movables",
    "nobility",
    "occasion",
    "ordering",
    "ornament",
    "outbreak",
    "outburst",
    "paroxysm",
    "patterns",
    "pedigree",
    "position",
    "practice",
    "practise",
    "precinct",
    "prestige",
    "priority",
    "progress",
    "proposal",
    "prospect",
    "protocol",
    "province",
    "purchase",
    "quandary",
    "rat race",
    "referral",
    "regalias",
    "research",
    "riggings",
    "road map",
    "sanction",
    "scenario",
    "schedule",
    "sentence",
    "showdown",
    "solution",
    "staffing",
    "standard",
    "standing",
    "stopover",
    "strategy",
    "taskwork",
    "think-in",
    "training",
    "transfer",
    "trapping",
    "trimming",
    "trinkets",
    "trumpery",
    "vacation",
    "vocation",
    "wardrobe",
    "warranty",
    "accessary",
    "accession",
    "accessory",
    "admission",
    "adornment",
    "advantage",
    "affidavit",
    "agreement",
    "allotment",
    "allowance",
    "amenities",
    "a move up",
    "animation",
    "anointing",
    "antiquity",
    "apparatus",
    "appendage",
    "appliance",
    "appointee",
    "armistice",
    "assigning",
    "assurance",
    "a step up",
    "authority",
    "auxiliary",
    "avocation",
    "bailiwick",
    "ball game",
    "baptismal",
    "barometer",
    "beginning",
    "behaviour",
    "benchmark",
    "bloodline",
    "blueprint",
    "breathing",
    "budgeting",
    "candidate",
    "celebrity",
    "character",
    "committal",
    "committee",
    "community",
    "component",
    "concordat",
    "concourse",
    "condition",
    "consensus",
    "conveying",
    "co-opting",
    "co-option",
    "criterion",
    "davenport",
    "delegates",
    "detailing",
    "diagnosis",
    "direction",
    "directive",
    "discharge",
    "disposing",
    "education",
    "eldership",
    "elevation",
    "embassage",
    "enactment",
    "encounter",
    "endeavour",
    "endowment",
    "enlisting",
    "enrolling",
    "enrolment",
    "equipages",
    "equipment",
    "equipping",
    "execution",
    "existence",
    "explosion",
    "extension",
    "figurines",
    "filiation",
    "firmament",
    "forebears",
    "formation",
    "furbelows",
    "furniture",
    "game plan",
    "garnishes",
    "gathering",
    "genealogy",
    "good name",
    "gradation",
    "greetings",
    "guarantee",
    "half a mo",
    "handcraft",
    "handshake",
    "happening",
    "heartbeat",
    "heritance",
    "hierarchy",
    "inaugural",
    "inception",
    "indenture",
    "induction",
    "influence",
    "intention",
    "interview",
    "invention",
    "investing",
    "isolating",
    "isolation",
    "jewelries",
    "judgement",
    "labelling",
    "launching",
    "laying on",
    "lifestyle",
    "life work",
    "love nest",
    "moonlight",
    "moveables",
    "moving up",
    "multitude",
    "nobleness",
    "objective",
    "operation",
    "ornaments",
    "panoplies",
    "parentage",
    "partition",
    "patronage",
    "placement",
    "play date",
    "prelation",
    "privilege",
    "programme",
    "promotion",
    "prorating",
    "providing",
    "provision",
    "purgation",
    "purveying",
    "rationing",
    "reception",
    "reference",
    "referring",
    "relations",
    "resources",
    "retaining",
    "selecting",
    "selection",
    "seniority",
    "sideboard",
    "situation",
    "soundings",
    "sparklers",
    "specialty",
    "specifics",
    "splitting",
    "spreading",
    "stockpile",
    "submittal",
    "supplying",
    "supremacy",
    "symposium",
    "taking in",
    "taking on",
    "tarriance",
    "territory",
    "time slot",
    "tour date",
    "trade-off",
    "transport",
    "trappings",
    "treasures",
    "trimmings",
    "twinkling",
    "two ticks",
    "upgrading",
    "variation",
    "voting in",
    "workplace",
    "yardstick",
    "zero hour",
    "acceptance",
    "accordance",
    "adaptation",
    "adjustment",
    "admittance",
    "adornments",
    "allocation",
    "alteration",
    "apotheosis",
    "appliances",
    "appointing",
    "argy-bargy",
    "ascription",
    "assemblage",
    "assessment",
    "assignment",
    "assumption",
    "attachment",
    "attainment",
    "background",
    "bedeckings",
    "bespeaking",
    "betterment",
    "blind date",
    "caparisons",
    "carving up",
    "catechesis",
    "collection",
    "colloquium",
    "commission",
    "commitment",
    "completion",
    "compliance",
    "compromise",
    "conception",
    "concession",
    "conclusion",
    "conditions",
    "conference",
    "conferment",
    "conferring",
    "confluence",
    "conformity",
    "connection",
    "consigning",
    "contingent",
    "convention",
    "conveyance",
    "coronation",
    "date night",
    "decoration",
    "dedication",
    "definition",
    "delegation",
    "delivering",
    "department",
    "deputation",
    "deputising",
    "deputizing",
    "derivation",
    "designings",
    "devolution",
    "difference",
    "disbursing",
    "discipline",
    "discussion",
    "dispensing",
    "dispersion",
    "divergence",
    "doling out",
    "earmarking",
    "emissaries",
    "employment",
    "empowering",
    "engagement",
    "enlistment",
    "enrollment",
    "enterprise",
    "enthroning",
    "entrusting",
    "equipments",
    "essentials",
    "estimation",
    "evaluation",
    "exaltation",
    "extraction",
    "extra part",
    "fandangles",
    "flourishes",
    "foundation",
    "fripperies",
    "furnishing",
    "garnitures",
    "giving out",
    "grindstone",
    "groupthink",
    "half a sec",
    "handicraft",
    "hearership",
    "heavy date",
    "importance",
    "imposition",
    "incumbency",
    "indicating",
    "indication",
    "indulgence",
    "initiation",
    "injunction",
    "instalment",
    "instrument",
    "investment",
    "invitation",
    "lifes work",
    "like it is",
    "livelihood",
    "meting out",
    "nanosecond",
    "nominating",
    "nomination",
    "obligation",
    "occupation",
    "occurrence",
    "onboarding",
    "one-to-one",
    "ordination",
    "passing on",
    "pigeonhole",
    "possession",
    "precedence",
    "preference",
    "preferment",
    "proceeding",
    "processing",
    "profession",
    "prominence",
    "purchasing",
    "putting in",
    "recruiting",
    "relegation",
    "relocation",
    "rendezvous",
    "reputation",
    "resolution",
    "retainment",
    "roundtable",
    "secondment",
    "separating",
    "separation",
    "setting up",
    "settlement",
    "short time",
    "signing on",
    "signing up",
    "size of it",
    "slicing up",
    "solitaires",
    "specialism",
    "speciality",
    "standpoint",
    "stationing",
    "statistics",
    "status quo",
    "submission",
    "submitting",
    "subvention",
    "succession",
    "suggestion",
    "supplement",
    "sustenance",
    "touchstone",
    "transferal",
    "trumperies",
    "two shakes",
    "visitation",
    "whats what",
    "accessories",
    "accrediting",
    "achievement",
    "acquisition",
    "adjudgement",
    "advancement",
    "affirmation",
    "application",
    "arbitrament",
    "arbitration",
    "arrangement",
    "assignation",
    "association",
    "attribution",
    "beautifiers",
    "beautifying",
    "before long",
    "bringing on",
    "cabinetwork",
    "calibration",
    "certificate",
    "chosen work",
    "circulating",
    "circulation",
    "common view",
    "composition",
    "concordance",
    "concurrence",
    "consequence",
    "consignment",
    "contingence",
    "contingency",
    "contracting",
    "convenience",
    "conventicle",
    "convergence",
    "convocation",
    "daily bread",
    "daily grind",
    "dealing out",
    "declaration",
    "decorations",
    "deification",
    "deliverance",
    "designating",
    "designation",
    "determining",
    "development",
    "dishing out",
    "disposition",
    "dissipating",
    "distinction",
    "dividing up",
    "divvying up",
    "double date",
    "empowerment",
    "enforcement",
    "ennoblement",
    "enrichments",
    "entitlement",
    "entrustment",
    "environment",
    "eventuality",
    "exaltedness",
    "examination",
    "expenditure",
    "exploration",
    "fallaleries",
    "family tree",
    "festoonings",
    "fifty-fifty",
    "furnishings",
    "giving over",
    "greater age",
    "ground plan",
    "half a tick",
    "handing out",
    "higher rank",
    "how it goes",
    "identifying",
    "impedimenta",
    "improvement",
    "ingathering",
    "installment",
    "instatement",
    "institution",
    "instruction",
    "interchange",
    "intercourse",
    "investiture",
    "jewelleries",
    "knickknacks",
    "lionisation",
    "lionization",
    "living wage",
    "lobby group",
    "maintenance",
    "master plan",
    "measurement",
    "microsecond",
    "millisecond",
    "near future",
    "negotiation",
    "nourishment",
    "objets dart",
    "opportunity",
    "orientation",
    "origination",
    "paramountcy",
    "passing out",
    "pinpointing",
    "positioning",
    "possessions",
    "possibility",
    "predicament",
    "proceedings",
    "progression",
    "propagation",
    "rap session",
    "recognition",
    "recruitment",
    "reservation",
    "restriction",
    "round robin",
    "round-robin",
    "round table",
    "sending out",
    "sharing out",
    "short while",
    "sovereignty",
    "stipulation",
    "subsistence",
    "sudden show",
    "superiority",
    "supplements",
    "sustainment",
    "swearing in",
    "swearing-in",
    "taking over",
    "termination",
    "tete-a-tete",
    "three winks",
    "transaction",
    "undertaking",
    "ventilation",
    "withholding",
    "working out",
    "accouterment",
    "accoutrement",
    "adjudication",
    "adjudicature",
    "alimentation",
    "amelioration",
    "appointments",
    "apportioning",
    "apprenticing",
    "appurtenance",
    "augmentation",
    "bedizenments",
    "buzz session",
    "carrying out",
    "circumstance",
    "coming weeks",
    "commencement",
    "compensation",
    "confirmation",
    "congregation",
    "conscription",
    "consecration",
    "consultation",
    "contribution",
    "conversation",
    "deliberation",
    "denominating",
    "denomination",
    "deputization",
    "disbursement",
    "dispensation",
    "distribution",
    "dividing out",
    "effectuation",
    "elaborations",
    "embellishers",
    "embroideries",
    "enhancements",
    "enthronement",
    "fixed object",
    "formal order",
    "garnishments",
    "get-together",
    "gingerbreads",
    "half measure",
    "handing over",
    "happenstance",
    "happy medium",
    "improvements",
    "inauguration",
    "installation",
    "intersection",
    "introduction",
    "jurisdiction",
    "line of work",
    "little while",
    "modification",
    "nine-to-five",
    "nothing flat",
    "officeholder",
    "ornatenesses",
    "package deal",
    "prescription",
    "presentation",
    "purification",
    "quid pro quo",
    "raison dêtre",
    "registration",
    "relationship",
    "remuneration",
    "sending away",
    "significance",
    "social class",
    "social group",
    "social order",
    "split second",
    "split-second",
    "surroundings",
    "sustentation",
    "tour of duty",
    "transference",
    "transferring",
    "walk of life",
    "where its at",
    "accommodation",
    "accouterments",
    "accoutrements",
    "accreditation",
    "admeasurement",
    "administering",
    "apportionment",
    "appropriation",
    "appurtenances",
    "area of study",
    "argumentation",
    "arranged date",
    "authorisation",
    "authorization",
    "bat of an eye",
    "bits and bobs",
    "brief display",
    "business deal",
    "certification",
    "chosen career",
    "circumstances",
    "coffee klatch",
    "coming months",
    "commissioning",
    "concentration",
    "confabulation",
    "confrontation",
    "consideration",
    "determination",
    "dignification",
    "dissemination",
    "embellishment",
    "establishment",
    "field of work",
    "foregathering",
    "fun and games",
    "give-and-take",
    "glorification",
    "gold standard",
    "half and half",
    "half a second",
    "half measures",
    "halfway house",
    "handing round",
    "illuminations",
    "incorporation",
    "kick upstairs",
    "magnification",
    "measuring out",
    "middle ground",
    "modus vivendi",
    "next few days",
    "office-holder",
    "ornamentation",
    "paraphernalia",
    "passing round",
    "pecking order",
    "piece of work",
    "preliminaries",
    "pronouncement",
    "rationing out",
    "reimbursement",
    "reserved room",
    "reserved seat",
    "setting aside",
    "sixty seconds",
    "social status",
    "specification",
    "state of play",
    "taking office",
    "understanding",
    "accompaniments",
    "acknowledgment",
    "administration",
    "aggrandisement",
    "aggrandizement",
    "back-and-forth",
    "bat of the eye",
    "being upgraded",
    "chance meeting",
    "classification",
    "cultural level",
    "embellishments",
    "heart-to-heart",
    "house fittings",
    "how things are",
    "identification",
    "implementation",
    "indoctrination",
    "in short order",
    "kettle of fish",
    "leading lights",
    "longer service",
    "neutral ground",
    "next few weeks",
    "no time at all",
    "ornamentations",
    "parcelling out",
    "piece of paper",
    "prearrangement",
    "recommendation",
    "reconciliation",
    "representative",
    "reserved table",
    "responsibility",
    "sanctification",
    "scheduled hour",
    "scheduled time",
    "second opinion",
    "secret meeting",
    "specialisation",
    "specialization",
    "transformation",
    "transportation",
    "way things are",
    "whats going on",
    "acknowledgement",
    "advance booking",
    "a kick upstairs",
    "assembled group",
    "baptism of fire",
    "beautifications",
    "bits and pieces",
    "blink of an eye",
    "coming together",
    "degree of merit",
    "experimentation",
    "household goods",
    "illicit meeting",
    "immortalization",
    "job opportunity",
    "lay of the land",
    "lie of the land",
    "line of country",
    "line of descent",
    "long row to hoe",
    "New York minute",
    "next few months",
    "one night stand",
    "one-night stand",
    "persons calling",
    "prestigiousness",
    "prettifications",
    "representatives",
    "reserved ticket",
    "rite de passage",
    "rite of passage",
    "social division",
    "social function",
    "social position",
    "social standing",
    "station in life",
    "vacant position",
    "a decision about",
    "area of interest",
    "bread and butter",
    "brief exhibition",
    "entente cordiale",
    "fifty-fifty deal",
    "how things stand",
    "immediate future",
    "line of business",
    "means of support",
    "meeting of minds",
    "military posting",
    "movable property",
    "opening ceremony",
    "panel discussion",
    "performance date",
    "personal effects",
    "predetermination",
    "situation vacant",
    "sixtieth of hour",
    "source of income",
    "state of affairs",
    "what one is into",
    "area of expertise",
    "costume jewelries",
    "degree of quality",
    "employment status",
    "hire arrangements",
    "less than no time",
    "particularization",
    "piece of business",
    "piece of research",
    "power of attorney",
    "prior arrangement",
    "social engagement",
    "source of revenue",
    "supervision order",
    "win-win situation",
    "career development",
    "diplomatic mission",
    "friendly agreement",
    "good understanding",
    "inaugural ceremony",
    "line of employment",
    "point on the scale",
    "prior arrangements",
    "rung on the ladder",
    "step up the ladder",
    "supplementary part",
    "clandestine meeting",
    "costume jewelleries",
    "how things stack up",
    "initiation ceremony",
    "means of livelihood",
    "medical appointment",
    "position in society",
    "sixtieth of an hour",
    "standing in society",
    "twinkling of an eye",
    "way things shape up",
    "a step up the ladder",
    "charter arrangements",
    "degree of competence",
    "exclusive possession",
    "fraction of a second",
    "gentlemans agreement",
    "gentlemens agreement",
    "level of achievement",
    "meeting of the minds",
    "mutual understanding",
    "set of circumstances",
    "degree of proficiency",
    "short stretch of time",
    "not too distant future",
    "position of employment",
    "international agreement",
    "supplementary component",
    "the twinkling of an eye",
    "means of earning a living",
    "two shakes of a lambs tail",
    "question and answer session",
    "means of earning ones living",
    "little bit",
    "fraction",
    "little",
    "small percentage",
    "tiny proportion",
    "bit",
    "mite",
    "scintilla",
    "tad",
    "speck",
    "smidgen",
    "crumb",
    "shred",
    "ounce",
    "hint",
    "scruple",
    "particle",
    "iota",
    "trace",
    "scrap",
    "morsel",
    "jot",
    "modicum",
    "whit",
    "lick",
    "smidge",
    "grain",
    "spot",
    "atom",
    "touch",
    "dash",
    "tittle",
    "drop",
    "dab",
    "molecule",
    "tinge",
    "snippet",
    "pinch",
    "dribble",
    "smidgeon",
    "scantling",
    "splash",
    "skosh",
    "strain",
    "spark",
    "suspicion",
    "nip",
    "spatter",
    "streak",
    "sprinkling",
    "driblet",
    "small amount",
    "glimmer",
    "shadow",
    "fragment",
    "dram",
    "ray",
    "shade",
    "granule",
    "dot",
    "fleck",
    "taste",
    "suggestion",
    "ace",
    "smack",
    "peanuts",
    "smell",
    "snap",
    "fig",
    "hoot",
    "rap",
    "snip",
    "diddly-squat",
    "continental",
    "bubkes",
    "ghost",
    "beans",
    "darn",
    "doodley-squat",
    "bupkes",
    "diddly",
    "durn",
    "whoop",
    "syllable",
    "squat",
    "doodly-squat",
    "sliver",
    "stim",
    "trifle",
    "sample",
    "patch",
    "nugget",
    "jot or tittle",
    "trickle",
    "soupçon",
    "mote",
    "piece",
    "minimum",
    "dollop",
    "shaving",
    "flyspeck",
    "nubbin",
    "whisper",
    "droplet",
    "sprinkle",
    "skerrick",
    "tiny piece",
    "tiniest bit",
    "tiny amount",
    "whiff",
    "detail",
    "any",
    "smitch",
    "bite",
    "nucleus",
    "infinitesimal",
    "corn",
    "some",
    "scoosh",
    "brush",
    "stroke",
    "drop in the bucket",
    "hairs breadth",
    "wee bit",
    "small bit",
    "shard",
    "small quantity",
    "chicken feed",
    "dose",
    "spoonful",
    "small portion",
    "snort",
    "stump",
    "small piece",
    "stub",
    "splinter",
    "shot",
    "specimen",
    "cast",
    "tiny bit",
    "vestige",
    "extract",
    "mouthful",
    "smudge",
    "smear",
    "blob",
    "slightly",
    "a smidgen",
    "proposal",
    "a suspicion",
    "a smack",
    "a tad",
    "semblance",
    "a modicum",
    "a suggestion",
    "somewhat",
    "distinction",
    "a dash",
    "spice",
    "a hint",
    "a bit",
    "a trace",
    "a touch",
    "rather",
    "a tinge",
    "amount",
    "a little",
    "blot",
    "peck",
    "portion",
    "tiny part",
    "inch",
    "smattering",
    "degree",
    "measure",
    "minim",
    "flicker",
    "breath",
    "intimation",
    "scent",
    "undertone",
    "tincture",
    "tang",
    "overtone",
    "element",
    "nuance",
    "inkling",
    "vein",
    "sparkle",
    "flash",
    "chip",
    "gleam",
    "glint",
    "indication",
    "glow",
    "sign",
    "quantity",
    "part",
    "flake",
    "paring",
    "sniff",
    "seed",
    "stitch",
    "soupç",
    "impression",
    "trait",
    "on",
    "thread",
    "air",
    "scattering",
    "segment",
    "powdering",
    "dust",
    "admixture",
    "mixture",
    "shake",
    "several",
    "tot",
    "slice",
    "shimmer",
    "tatter",
    "nit",
    "bug",
    "parasite",
    "acarid",
    "insect",
    "tick",
    "minute",
    "twinkle",
    "blink",
    "arc",
    "spit",
    "beam",
    "cantlet",
    "lump",
    "section",
    "chunk",
    "tidbit",
    "strand",
    "tendency",
    "note",
    "slug",
    "glass",
    "sip",
    "thimbleful",
    "drink",
    "finger",
    "snifter",
    "hunk",
    "murmur",
    "glitter",
    "smithereen",
    "slightest bit",
    "draft",
    "weight",
    "swig",
    "gobbet",
    "colouring",
    "path",
    "trail",
    "footstep",
    "track",
    "excerpt",
    "snatch",
    "coloring",
    "footprint",
    "footmark",
    "glance",
    "coruscation",
    "scintillation",
    "shine",
    "draught",
    "a small sum",
    "a trifling amount",
    "a paltry sum",
    "a trifling sum",
    "footpath",
    "pathway",
    "step",
    "slot",
    "spoor",
    "butt",
    "parcel",
    "end",
    "moiety",
    "division",
    "item",
    "niggle",
    "share",
    "scale",
    "nib",
    "record",
    "tread",
    "memento",
    "residue",
    "proof",
    "token",
    "electronic footprint",
    "soupcon",
    "hair",
    "small degree",
    "pittance",
    "no big deal",
    "trifling amount",
    "fly speck",
    "hardly anything",
    "very small amount",
    "next to nothing",
    "piddling amount",
    "chump change",
    "fraction",
    "fragment",
    "selection",
    "smattering",
    "snatch",
    "snippet",
    "tiny part"
  ])
];
const CODE = [...new Set(["algos", "algo", "coder", "code"])];
const TRAIN = [
  ...new Set([
    "solve",
    "train",
    "practice",
    "shape",
    "training",
    "drill",
    "rehearsal",
    "study",
    "exercise",
    "preparation",
    "repetition",
    "discipline",
    "routine",
    "run-through",
    "trial",
    "workout",
    "work-out",
    "dry run",
    "shootaround",
    "try-out",
    "warm-up",
    "background",
    "drilling",
    "dummy run",
    "effect",
    "experience",
    "iteration",
    "practice session",
    "prepping",
    "recitation",
    "recounting",
    "relating",
    "seasoning",
    "tune-up",
    "assignment",
    "homework",
    "tryout",
    "practise",
    "test",
    "trial run",
    "run through",
    "instruction",
    "evacuation",
    "fire practice",
    "fire drill",
    "examination",
    "test run",
    "shakedown",
    "evaluation",
    "audition",
    "assessment",
    "knockabout",
    "conditioning",
    "training session",
    "education",
    "walk-through",
    "knock-up",
    "dress rehearsal",
    "maneuvers",
    "experiment",
    "reading",
    "teaching",
    "manoeuvres",
    "coaching",
    "grounding",
    "call",
    "exercises",
    "readying",
    "working out",
    "gym",
    "keeping fit",
    "constitutional",
    "physical activity",
    "daily dozen",
    "praxis",
    "run",
    "tech rehearsal",
    "technical run",
    "gypsy rehearsal",
    "final dress",
    "tech run",
    "full rehearsal",
    "maneuver",
    "kriegspiel",
    "square-bashing",
    "marching",
    "dress",
    "aerobics",
    "physical exercise",
    "friendly",
    "game",
    "matriculation",
    "schooling",
    "physical exercises",
    "callisthenics",
    "isometrics",
    "gymnastics",
    "bodybuilding",
    "body building",
    "tutelage",
    "learning by doing",
    "test performance",
    "practical test",
    "practice run",
    "manoeuvre",
    "bench test",
    "practice exercise",
    "war game",
    "road test",
    "combat rehearsal",
    "weightlifting",
    "exercise session",
    "session",
    "work",
    "keep-fit session",
    "limbering up",
    "calisthenics",
    "tuition",
    "tutoring",
    "physical training session",
    "keep fit",
    "indoctrination",
    "priming",
    "guidance",
    "pedagogy",
    "andragogy",
    "lessons",
    "inculcation",
    "sharpening",
    "upbringing",
    "cultivation",
    "module",
    "workshop",
    "going-over",
    "schoolwork",
    "tutorial",
    "chalk talk",
    "activity",
    "fitness",
    "telling",
    "list",
    "rehearsing",
    "description",
    "sing-through",
    "relation",
    "read-through",
    "recital",
    "account",
    "exercising",
    "informal game",
    "friendly game",
    "exertion",
    "movement",
    "sports",
    "enumeration",
    "catalogue",
    "trial performance",
    "narration",
    "check",
    "testing",
    "assay",
    "quiz",
    "school task",
    "lesson",
    "academic work",
    "school work",
    "task",
    "workouts",
    "staying fit",
    "probation",
    "attempt",
    "physical training",
    "physical movements",
    "prep",
    "catalog",
    "retelling",
    "crack",
    "shot",
    "go",
    "essay",
    "try",
    "appraisal",
    "action",
    "stab",
    "whack",
    "games",
    "offer",
    "pass",
    "venture",
    "experimentation",
    "fling",
    "effort",
    "bash",
    "bid",
    "proof",
    "whirl",
    "endeavor",
    "drills",
    "a workout",
    "trial balloon",
    "test flight",
    "physical education",
    "test-run",
    "endeavour",
    "test period",
    "analysis",
    "showcase",
    "lick",
    "undertaking",
    "striving",
    "trial period",
    "struggle",
    "pilot study",
    "investigation",
    "screen test",
    "try on",
    "research and development",
    "R and D",
    "trial and error",
    "profession",
    "career",
    "work",
    "business",
    "occupation",
    "pursuit",
    "following",
    "vocation",
    "employment",
    "job",
    "line",
    "trade",
    "calling",
    "day job",
    "mission",
    "lifework",
    "line of business",
    "lifes work",
    "field",
    "line of work",
    "walk of life",
    "department",
    "rank",
    "status",
    "class",
    "arena",
    "area",
    "caste",
    "domain",
    "sphere",
    "station",
    "realm",
    "craft",
    "province",
    "chosen career",
    "engagement",
    "position",
    "office",
    "placement",
    "practise",
    "post",
    "connection",
    "gig",
    "hire",
    "capacity",
    "employment status",
    "spot",
    "appointment",
    "task",
    "racket",
    "living",
    "posting",
    "livelihood",
    "service",
    "duty",
    "berth",
    "place",
    "billet",
    "grip",
    "situation",
    "game",
    "function",
    "métier",
    "employ",
    "role",
    "thing",
    "nine-to-five",
    "slot",
    "rat race",
    "niche",
    "way",
    "lay",
    "handicraft",
    "walk",
    "opening",
    "dodge",
    "art",
    "stint",
    "activity",
    "specialty",
    "speciality",
    "chosen work",
    "what one is into",
    "means",
    "vacancy",
    "assignment",
    "contract",
    "part",
    "purpose",
    "daily grind",
    "enterprise",
    "avocation",
    "do",
    "bag",
    "day gig",
    "undertaking",
    "subsistence",
    "opportunity",
    "maintenance",
    "sustenance",
    "skill",
    "income",
    "grind",
    "swindle",
    "keep",
    "hiring",
    "discipline",
    "element",
    "circle",
    "front",
    "upkeep",
    "nourishment",
    "hang",
    "play",
    "demesne",
    "barony",
    "bailiwick",
    "specialization",
    "fief",
    "fiefdom",
    "means of support",
    "firmament",
    "funds",
    "source of income",
    "concern",
    "alimentation",
    "source of revenue",
    "support",
    "biz",
    "bread and butter",
    "line of country",
    "daily bread",
    "line of employment",
    "specialisation",
    "labour",
    "labor",
    "setup",
    "handcraft",
    "position of employment",
    "gap",
    "vacuum",
    "faculty",
    "field of work",
    "metier",
    "go",
    "industry",
    "sector",
    "patronage",
    "custom",
    "charge",
    "means of livelihood",
    "job opportunity",
    "world",
    "commitment",
    "obligation",
    "means of earning a living",
    "terrain",
    "jurisdiction",
    "zone",
    "territory",
    "vacant position",
    "means of earning ones living",
    "contracting",
    "recruitment",
    "placing",
    "brief",
    "turf",
    "bubble",
    "precinct",
    "section",
    "sport",
    "situation vacant",
    "life work",
    "commission",
    "orbit",
    "proceeding",
    "kingdom",
    "being",
    "existence",
    "lick",
    "grindstone",
    "affair",
    "moonlight",
    "detail",
    "operation",
    "area of study",
    "area of interest",
    "life",
    "existing",
    "animation",
    "sustainment",
    "apprenticing",
    "enrolling",
    "enlisting",
    "enrolment",
    "enrollment",
    "workplace",
    "forte",
    "living wage",
    "salt",
    "mode",
    "sustentation",
    "interest",
    "persons calling",
    "area of expertise",
    "specialism",
    "circumstances",
    "resources",
    "experience",
    "knowledge",
    "skill",
    "wisdom",
    "expertise",
    "exposure",
    "familiarity",
    "involvement",
    "proficiency",
    "skills",
    "capability",
    "competence",
    "insight",
    "intimacy",
    "know-how",
    "mastery",
    "practical knowledge",
    "savvy",
    "training",
    "understanding",
    "acumen",
    "command",
    "impression",
    "judgement",
    "judgment",
    "maturity",
    "perspicacity",
    "professionalism",
    "qualification",
    "qualifications",
    "savoir-faire",
    "talent",
    "worldliness",
    "acquaintance",
    "action",
    "authority",
    "comprehension",
    "contact",
    "conversance",
    "education",
    "finesse",
    "grounding",
    "learning",
    "smarts",
    "ability",
    "awareness",
    "capacity",
    "common sense",
    "development",
    "dexterity",
    "discretion",
    "distinction",
    "doing",
    "efficiency",
    "empiricism",
    "enlightenment",
    "evidence",
    "expertness",
    "faculty",
    "fitness",
    "foresight",
    "grasp",
    "gumption",
    "hindsight",
    "inclination",
    "intelligence",
    "intuitiveness",
    "knack",
    "life skills",
    "perception",
    "power",
    "profundity",
    "proof",
    "prowess",
    "prudence",
    "rationality",
    "reason",
    "refinement",
    "resourcefulness",
    "work",
    "job",
    "responsibility",
    "duty",
    "endeavour",
    "endeavor",
    "task",
    "undertaking",
    "activity",
    "art",
    "assignment",
    "craft",
    "occupation",
    "role",
    "business",
    "chores",
    "commission",
    "function",
    "industry",
    "obligation",
    "purpose",
    "service",
    "brief",
    "charge",
    "métier",
    "mission",
    "niche",
    "setup",
    "commitment",
    "process",
    "project",
    "servitude",
    "situation",
    "use",
    "focus",
    "capacity",
    "concern",
    "involvement",
    "part",
    "participation",
    "place",
    "rôle",
    "exercise",
    "post",
    "chore",
    "detail",
    "engagement",
    "errand",
    "labour",
    "position",
    "appointment",
    "office",
    "operation",
    "enterprise",
    "stint",
    "beat",
    "labor",
    "piece of work",
    "piece of business",
    "discipline",
    "field",
    "area",
    "domain",
    "sphere",
    "subject",
    "business",
    "department",
    "realm",
    "speciality",
    "specialty",
    "arena",
    "circle",
    "line",
    "topic",
    "walk",
    "bailiwick",
    "barony",
    "course",
    "curriculum",
    "element",
    "firmament",
    "province",
    "terrain",
    "theme",
    "exercise",
    "fief",
    "fiefdom",
    "method",
    "branch of knowledge",
    "field of inquiry",
    "field of study",
    "front",
    "game",
    "kingdom",
    "mastery",
    "precinct",
    "subject matter",
    "area of study",
    "branch of learning",
    "course of study",
    "specialist subject",
    "demesne",
    "territory",
    "orbit",
    "jurisdiction",
    "sector",
    "world",
    "calling",
    "turf",
    "forte",
    "vocation",
    "dominion",
    "occupation",
    "profession",
    "capacity",
    "work",
    "zone",
    "employment",
    "métier",
    "section",
    "activity",
    "job",
    "trade",
    "racket",
    "scene",
    "thing",
    "preserve",
    "career",
    "concern",
    "sphere of influence",
    "specialism",
    "region",
    "walk of life",
    "pursuit",
    "specialization",
    "area of interest",
    "sphere of activity",
    "line of work",
    "line of business",
    "milieu",
    "metier",
    "scope",
    "purview",
    "function",
    "specialisation",
    "pigeon",
    "post",
    "area of activity",
    "craft",
    "responsibility",
    "environment",
    "study",
    "duty",
    "society",
    "charge",
    "branch",
    "part",
    "niche",
    "authority",
    "role",
    "compass",
    "affair",
    "division",
    "position",
    "interest",
    "avocation",
    "area of responsibility",
    "area of knowledge",
    "range",
    "office",
    "patch",
    "bag",
    "class",
    "station",
    "slot",
    "ground",
    "line of country",
    "skill",
    "neck of the woods",
    "area of expertise",
    "day job",
    "skills",
    "market",
    "manor",
    "seigniory",
    "medium",
    "compartment",
    "turfdom",
    "breadth",
    "beat",
    "operation",
    "life",
    "ambit",
    "stage",
    "branch of study",
    "task",
    "theatre",
    "forum",
    "industry",
    "system",
    "persons calling",
    "baby",
    "battlefield",
    "battleground",
    "engagement",
    "enterprise",
    "school",
    "field of influence",
    "area of power",
    "rank",
    "administration",
    "berth",
    "classification",
    "spot",
    "incumbency",
    "assignment",
    "group",
    "living",
    "service",
    "neighbourhood",
    "state",
    "radius",
    "neighborhood",
    "expanse",
    "place",
    "dimension",
    "extent",
    "stratum",
    "remit",
    "status",
    "handicraft",
    "situation",
    "bubble",
    "sport",
    "lists",
    "area of influence",
    "jungle",
    "proceeding",
    "undertaking",
    "pursuits",
    "matters",
    "handcraft",
    "art",
    "way",
    "theater",
    "stomping grounds",
    "handiwork",
    "employ",
    "grip",
    "faculty",
    "chosen work",
    "rat race",
    "line of employment",
    "sphere of action",
    "area of conflict",
    "field of conflict",
    "tier",
    "worry",
    "county",
    "champaign",
    "shire",
    "tract",
    "prefecture",
    "gift",
    "mission",
    "knack",
    "inclination",
    "genius",
    "flair",
    "strong suit",
    "aptitude",
    "ability",
    "bent",
    "disposition",
    "talent",
    "leaning",
    "margin",
    "confines",
    "pale",
    "sphere of study",
    "sphere of interest",
    "land",
    "district",
    "country",
    "estate",
    "lands",
    "enclave",
    "empire",
    "colony",
    "quarter",
    "dominions",
    "property",
    "belt",
    "area of land",
    "tract of land",
    "dependency",
    "possession",
    "holding",
    "protectorate",
    "nation",
    "soil",
    "town",
    "township",
    "category",
    "pitch",
    "exclave",
    "mandate",
    "type",
    "order",
    "categorization",
    "grade",
    "genre",
    "bracket",
    "grouping",
    "variety",
    "family",
    "cast",
    "wing",
    "stamping ground",
    "home park",
    "culture",
    "refinement",
    "polish",
    "education",
    "cultivation",
    "enlightenment",
    "sophistication",
    "accomplishment",
    "urbanity",
    "discernment",
    "discrimination",
    "erudition",
    "taste",
    "breeding",
    "civilisation",
    "civilization",
    "couth",
    "learning",
    "worldliness",
    "artistic awareness",
    "belles-lettres",
    "gentility",
    "intellectual awareness",
    "letters",
    "urbaneness",
    "ability",
    "address",
    "aestheticism",
    "art",
    "capacity",
    "class",
    "courtesy",
    "delicacy",
    "dignity",
    "dress",
    "elegance",
    "elevation",
    "experience",
    "fashion",
    "finish",
    "good taste",
    "grace",
    "kindness",
    "manners",
    "nobility",
    "perception",
    "politeness",
    "proficiency",
    "savoir-faire",
    "science",
    "skill",
    "tact",
    "training",
    "improvement",
    "civility",
    "courtliness",
    "graciousness",
    "style",
    "scholarship",
    "knowledge",
    "courteousness",
    "literacy",
    "good manners",
    "mannerliness",
    "good breeding",
    "genteelness",
    "edification",
    "learnedness",
    "schooling",
    "distinction",
    "finesse",
    "amenities",
    "ceremony",
    "affability",
    "suavity",
    "politesse",
    "wisdom",
    "decorum",
    "deference",
    "book learning",
    "gallantry",
    "chivalry",
    "consideration",
    "complaisance",
    "instruction",
    "study",
    "propriety",
    "information",
    "insight",
    "etiquette",
    "judgment",
    "cordiality",
    "acumen",
    "amiability",
    "comity",
    "attentiveness",
    "familiarity",
    "friendliness",
    "teaching",
    "respect",
    "gentleness",
    "thoughtfulness",
    "gallantness",
    "suaveness",
    "tastefulness",
    "poise",
    "nicety",
    "correctness",
    "background",
    "nurture",
    "illumination",
    "understanding",
    "judgement",
    "discretion",
    "favor",
    "intellect",
    "intelligence",
    "geniality",
    "tuition",
    "reverence",
    "solicitude",
    "sympathy",
    "tutelage",
    "sagacity",
    "appreciation",
    "conduct",
    "pedagogy",
    "chic",
    "gracefulness",
    "stylishness",
    "restraint",
    "smoothness",
    "brainwashing",
    "catechism",
    "direction",
    "indoctrination",
    "apprenticeship",
    "reading",
    "inculcation",
    "proselytism",
    "rearing",
    "acuteness",
    "tutoring",
    "advancement",
    "subtlety",
    "sageness",
    "attainments",
    "charm",
    "grandeur",
    "majesty",
    "elegancy",
    "development",
    "stateliness",
    "lore",
    "favour",
    "propagandism",
    "good behavior",
    "classiness",
    "awareness",
    "literature",
    "magnificence",
    "indulgence",
    "generosity",
    "splendor",
    "hauteur",
    "pedagogics",
    "splendour",
    "diplomacy",
    "beauty",
    "respectfulness",
    "discipline",
    "coaching",
    "drilling",
    "guidance",
    "preparation",
    "humanities",
    "carriage",
    "behavior",
    "comportment",
    "civilities",
    "mores",
    "bearing",
    "demeanor",
    "formalities",
    "mien",
    "protocol",
    "deportment",
    "progress",
    "penetration",
    "astuteness",
    "accomplishments",
    "gentlemanliness",
    "expertise",
    "respectability",
    "acquirements",
    "shrewdness",
    "tactfulness",
    "sumptuousness",
    "good form",
    "fineness",
    "knowingness",
    "cool",
    "culturedness",
    "handsomeness",
    "luxury",
    "exquisiteness",
    "seemliness",
    "formality",
    "decorousness",
    "self-possession",
    "ps and qs",
    "fastidiousness",
    "panache",
    "noblesse",
    "poshness",
    "rhythm",
    "felicity",
    "symmetry",
    "lushness",
    "ornateness",
    "purity",
    "behaviour",
    "demeanour",
    "comprehension",
    "rank",
    "academic attainment",
    "savvy",
    "composure",
    "book-learning",
    "soft skills",
    "decency",
    "attractiveness",
    "feeling",
    "susceptibility",
    "gallantr",
    "books",
    "control",
    "acceptable conduct",
    "correct behaviour",
    "polite behaviour",
    "polites",
    "convention",
    "letter",
    "academic training",
    "grounding",
    "thought",
    "plushness",
    "opulence",
    "flair",
    "dash",
    "manner",
    "polite",
    "swankiness",
    "cultivated look",
    "social standing",
    "considerateness",
    "andragogy",
    "lessons",
    "smartness",
    "modishness",
    "refined taste",
    "savoir-vivre",
    "obligingness",
    "done thing",
    "formal education",
    "worldly wisdom",
    "savoir faire",
    "common courtesy",
    "cultivated beauty",
    "bookishness",
    "studiousness",
    "brains",
    "intellectuality",
    "scholarliness",
    "pedantry",
    "scholarism",
    "open-mindedness",
    "broad-mindedness",
    "precision",
    "light",
    "perspicacity",
    "social graces",
    "savoir vivre",
    "social grace",
    "awakening",
    "liberalism",
    "nous",
    "perceptivity",
    "sapience",
    "perceptiveness",
    "empire",
    "evolution",
    "acculturation",
    "polity",
    "human development",
    "nuance",
    "higher education",
    "academic knowledge",
    "explanation",
    "satori",
    "epiphany",
    "bodhi",
    "clarification",
    "maturity",
    "know-how",
    "grasp",
    "research",
    "philosophy",
    "cognition",
    "selectivity",
    "separation",
    "demarcation",
    "sensitivity",
    "judiciousness",
    "percipience",
    "discreteness",
    "intellectual attainment",
    "academic achievement",
    "social well-being",
    "acuity",
    "keenness",
    "sense",
    "connoisseurship",
    "smarts",
    "clearness",
    "fine tuning",
    "academic study",
    "astucity",
    "peace that passeth understanding",
    "an aha moment",
    "expertness",
    "prudence",
    "mastery",
    "foresight",
    "doctrine",
    "omniscience",
    "adeptness",
    "fine point",
    "land of the living",
    "ladylikeness",
    "loftiness",
    "solemnity",
    "nobleness",
    "punctiliousness",
    "regalness",
    "impressiveness",
    "royalness",
    "regard",
    "honor",
    "regality",
    "ostentatiousness",
    "affectation",
    "ostentation",
    "affectedness",
    "augustness",
    "exaltedness",
    "integrity",
    "gravitas",
    "worthiness",
    "lordliness",
    "ceremoniousness",
    "society",
    "optimacy",
    "flower",
    "modesty",
    "honourability",
    "renown",
    "righteousness",
    "state",
    "standing",
    "gravity",
    "sedateness",
    "reserve",
    "sobriety",
    "character",
    "quality",
    "excellence",
    "station",
    "ruling class",
    "blue blood",
    "high birth",
    "stature",
    "ethics",
    "significance",
    "sublimity",
    "morality",
    "consequence",
    "seriousness",
    "goodness",
    "worth",
    "honour",
    "merit",
    "virtue",
    "cachet",
    "perfection",
    "gentle birth",
    "good family",
    "repetition",
    "iteration",
    "reiteration",
    "duplication",
    "repeating",
    "restatement",
    "recapitulation",
    "replication",
    "reprise",
    "iterance",
    "recital",
    "recurrence",
    "redo",
    "redundancy",
    "reduplication",
    "rehearsal",
    "renewal",
    "repeat",
    "replay",
    "retelling",
    "echo",
    "reappearance",
    "recap",
    "repetitiousness",
    "tautology",
    "alliteration",
    "chant",
    "chorus",
    "copy",
    "encore",
    "ingemination",
    "iteracy",
    "litany",
    "paraphrase",
    "periodicity",
    "perseveration",
    "relation",
    "report",
    "reproduction",
    "return",
    "reverberation",
    "rhythm",
    "rote",
    "staccato",
    "broken record",
    "emphasis",
    "monotony",
    "rerun",
    "rhyme",
    "echoing",
    "similarity",
    "copying",
    "photocopying",
    "verbiage",
    "verbosity",
    "another go",
    "replicating",
    "duplicating",
    "xeroxing",
    "pleonasm",
    "repetitiveness",
    "prolixity",
    "assonance",
    "photostating",
    "photostatting",
    "reprinting",
    "repeat attempt",
    "long-windedness",
    "superfluity",
    "periphrasis",
    "wordiness",
    "doubling",
    "perissology",
    "retry",
    "specialty",
    "forte",
    "thing",
    "metier",
    "speciality",
    "long suit",
    "strong suit",
    "career",
    "hobby",
    "job",
    "major",
    "masterpiece",
    "minor",
    "number",
    "occupation",
    "profession",
    "pursuit",
    "racket",
    "special",
    "vocation",
    "weakness",
    "work",
    "distinguishing feature",
    "magnum opus",
    "special project",
    "claim to fame",
    "cup of tea",
    "field of concentration",
    "object of attention",
    "object of study",
    "piece de resistance",
    "métier",
    "strength",
    "strong point",
    "skill",
    "gift",
    "talent",
    "aptitude",
    "bent",
    "ability",
    "asset",
    "tier",
    "bag",
    "department",
    "line",
    "craft",
    "calling",
    "efficiency",
    "ableness",
    "competence",
    "eminency",
    "faculty",
    "medium",
    "effectiveness",
    "oyster",
    "sphere",
    "special asset",
    "trade",
    "special ability",
    "likable trait",
    "good points",
    "redeeming quality",
    "redeeming feature",
    "lifework",
    "business",
    "knack",
    "inclination",
    "advantage",
    "leaning",
    "discipline",
    "flair",
    "province",
    "mission",
    "field",
    "domain",
    "disposition",
    "arena",
    "area",
    "genius",
    "realm",
    "virtue",
    "distinctive",
    "expertise",
    "pith",
    "connection",
    "in",
    "sense",
    "capability",
    "succor",
    "succour",
    "body",
    "core",
    "license",
    "wire",
    "burden",
    "security",
    "purport",
    "gist",
    "meat",
    "special talent",
    "pièce de résistance",
    "upper hand",
    "intestinal fortitude",
    "special subject",
    "athletics",
    "games",
    "races",
    "sports",
    "exercises",
    "contests",
    "P.E.",
    "gymnastics",
    "matches",
    "competitions",
    "palaestra",
    "contest",
    "drill",
    "events",
    "organized games",
    "recreation",
    "training",
    "workout",
    "sporting events",
    "games of strength",
    "physical education",
    "sporting contests",
    "sports activities",
    "sports competitions",
    "sports events",
    "track-and-field events",
    "track and field events",
    "aerobics",
    "exercise",
    "phys ed",
    "gymnastic",
    "gym class",
    "calisthenics",
    "callisthenics",
    "sports education",
    "physical training",
    "lesson",
    "class",
    "session",
    "lecture",
    "period",
    "seminar",
    "tutorial",
    "subject",
    "coaching",
    "course",
    "instruction",
    "schooling",
    "teaching",
    "tutoring",
    "education",
    "lear",
    "learning",
    "study",
    "training",
    "chalk talk",
    "period of coaching",
    "period of instruction",
    "period of schooling",
    "period of teaching",
    "period of tutoring",
    "information taught",
    "workshop",
    "academy",
    "course of study",
    "lecture group",
    "discussion group",
    "clinic",
    "masterclass",
    "tute",
    "study group",
    "individual instruction",
    "program",
    "curriculum",
    "discussion",
    "module",
    "programme",
    "homeroom",
    "recitation",
    "colloquium",
    "prospectus",
    "studies",
    "schedule",
    "syllabus",
    "laboratory",
    "conference",
    "classes",
    "exercise",
    "assignment",
    "drill",
    "round table",
    "programme of study",
    "set of lectures",
    "educational programme",
    "quiz group",
    "school work",
    "lecture series",
    "educational program",
    "programme of studies",
    "program of studies",
    "course of studies",
    "rehearse",
    "exercise",
    "study",
    "hone",
    "sharpen",
    "train",
    "work",
    "attempt",
    "iterate",
    "polish",
    "repeat",
    "try",
    "drill",
    "habituate",
    "prepare",
    "recite",
    "run over",
    "shake-down",
    "become seasoned",
    "build up",
    "do again",
    "dress rehearse",
    "dry run",
    "go over",
    "go through",
    "run through",
    "try out",
    "tune up",
    "walk through",
    "warm up",
    "work out",
    "practise",
    "loosen up",
    "get ready",
    "coach",
    "get into shape",
    "accustom",
    "spar",
    "shadowbox",
    "stretch",
    "sing through",
    "read through",
    "limber up",
    "get into condition",
    "run down",
    "teach",
    "instruct",
    "discipline",
    "ground",
    "inculcate",
    "adapt",
    "inure",
    "groom",
    "make fit",
    "school",
    "lick into shape",
    "break",
    "put someone through their paces",
    "break in",
    "work over",
    "season",
    "get used to",
    "toughen up",
    "condition",
    "whip into shape",
    "equip",
    "shape up",
    "perfect",
    "refine",
    "do",
    "work on",
    "work at",
    "do exercises",
    "keep your hand in",
    "knock up",
    "list",
    "detail",
    "describe",
    "recount",
    "tell",
    "enumerate",
    "reiterate",
    "relate",
    "review",
    "itemize",
    "recapitulate",
    "narrate",
    "specify",
    "name",
    "present",
    "delineate",
    "din",
    "act",
    "chime",
    "reel off",
    "give",
    "catalogue",
    "tick off",
    "numerate",
    "depict",
    "restate",
    "ready",
    "report",
    "chart",
    "chronicle",
    "set out",
    "spell out",
    "recap",
    "catalog",
    "experiment",
    "do over",
    "rattle off",
    "test",
    "run lines",
    "itemise",
    "reenact",
    "take from the top",
    "learn ones part",
    "hold a reading",
    "trot out",
    "perform",
    "apply",
    "do",
    "pursue",
    "execute",
    "follow",
    "observe",
    "ply",
    "fulfil",
    "fulfill",
    "carry out",
    "engage in",
    "live out",
    "specialize in",
    "work at",
    "live up to",
    "put into effect",
    "put into practice",
    "carry on",
    "conduct",
    "practise",
    "prosecute",
    "wage",
    "proceed with",
    "undertake",
    "continue",
    "fight",
    "continue with",
    "keep on with",
    "devote oneself to",
    "go on with",
    "go ahead with",
    "see through",
    "direct",
    "manage",
    "maintain",
    "tackle",
    "discharge",
    "persist",
    "persevere",
    "apply oneself to",
    "stick at",
    "participate in",
    "proceed in",
    "keep on",
    "adhere to",
    "proceed",
    "stick with",
    "adhere",
    "devote yourself to",
    "be engaged in",
    "apply oneself",
    "go in for",
    "take up",
    "apply yourself to",
    "take further",
    "take part in",
    "be occupied in",
    "carry on with",
    "hold to",
    "cultivate",
    "persist in",
    "persevere in",
    "carry through",
    "follow up",
    "follow through",
    "instigate",
    "make",
    "exercise",
    "busy oneself with",
    "occupy oneself with",
    "have a career in",
    "ply your trade",
    "pursue a career in",
    "exercise",
    "practise",
    "apply",
    "use",
    "wield",
    "effect",
    "employ",
    "engage",
    "execute",
    "exert",
    "exploit",
    "harness",
    "utilise",
    "utilize",
    "implement",
    "ply",
    "deploy",
    "operate",
    "realise",
    "realize",
    "tap",
    "put into action",
    "put into practice",
    "bring into play",
    "carry out",
    "draw on",
    "put to use",
    "put to work",
    "bring to bear",
    "call upon",
    "put into effect",
    "set in motion",
    "call into play",
    "capitalize on",
    "make use of",
    "play on",
    "put forth",
    "put in motion",
    "avail oneself of",
    "avail yourself of",
    "make the most of",
    "do",
    "handle",
    "enact",
    "put out",
    "achieve",
    "accomplish",
    "manoeuvre",
    "maneuver",
    "administer",
    "prosecute",
    "enforce",
    "assign",
    "regulate",
    "source",
    "manage",
    "bring into effect",
    "manipulate",
    "work",
    "put into operation",
    "swing",
    "work with",
    "function",
    "wage",
    "dispense",
    "throw",
    "perform",
    "produce",
    "complete",
    "engage in",
    "commit",
    "initiate",
    "act",
    "finish",
    "pull off",
    "bring off",
    "make",
    "act out",
    "specialize",
    "concentrate",
    "focus",
    "major in",
    "train",
    "dedicate yourself to",
    "practise",
    "pursue",
    "be into",
    "develop oneself in",
    "do ones thing",
    "go in for",
    "have a weakness for",
    "limit oneself to",
    "practice exclusively",
    "study intensively",
    "work in",
    "polish up on",
    "brush up",
    "enhance",
    "hone",
    "improve",
    "perfect",
    "refine",
    "work on",
    "polish",
    "better",
    "polish up",
    "develop",
    "work up",
    "build up",
    "sharpen",
    "upgrade",
    "prepare",
    "augment",
    "groom",
    "help",
    "correct",
    "finish",
    "emend",
    "embellish",
    "rephrase",
    "consummate",
    "copy-edit",
    "rewrite",
    "revise",
    "finalize",
    "complete",
    "cultivate",
    "rescript",
    "improve performance",
    "mature",
    "put the finishing touches to",
    "clean up",
    "go over",
    "sleek",
    "put the final touches to",
    "slick",
    "finalise",
    "amend",
    "finish off",
    "round",
    "make improvement",
    "touch up",
    "mend",
    "practise",
    "advance",
    "ameliorate",
    "progress",
    "further",
    "grow",
    "elevate",
    "propel",
    "build",
    "take the next step",
    "gain ground",
    "make strides",
    "complement",
    "optimize",
    "revamp",
    "strengthen",
    "enrich",
    "soup up",
    "spruce up",
    "supplement",
    "fine-tune",
    "meliorate",
    "smarten",
    "optimise",
    "take to the next level",
    "fortify",
    "add value to",
    "raise",
    "lift",
    "boost",
    "train",
    "push ahead",
    "bolster",
    "push on",
    "hasten",
    "promote",
    "launch",
    "move forward",
    "get with it",
    "forge ahead with",
    "make headway with",
    "press on",
    "press forward",
    "bring forward",
    "multiply",
    "prosper",
    "continue ahead",
    "thrive",
    "take it to the next level",
    "come on",
    "get ahead of",
    "devote yourself to",
    "get better at",
    "devote oneself to",
    "work hard at",
    "build on",
    "brush up on",
    "adhere",
    "follow",
    "heed",
    "maintain",
    "obey",
    "observe",
    "support",
    "uphold",
    "practise",
    "respect",
    "fulfil",
    "fulfill",
    "mind",
    "abide by",
    "stand by",
    "stick to",
    "be faithful to",
    "comply with",
    "conform to",
    "hold to",
    "keep to",
    "stick with",
    "sticky by",
    "be devoted to",
    "be guided by",
    "be loyal to",
    "cleave to",
    "cooperate with",
    "go along with",
    "remain true to",
    "submit to",
    "take to heart",
    "act in accordance with",
    "pay attention to",
    "pay regard to",
    "bear in mind",
    "be attached",
    "be constant",
    "be devoted",
    "be faithful",
    "be loyal",
    "be true",
    "cling",
    "cling to",
    "hold",
    "engage",
    "participate",
    "join",
    "partake",
    "abet",
    "collaborate",
    "contribute",
    "cooperate",
    "play",
    "undertake",
    "share",
    "enter",
    "practise",
    "become involved",
    "tackle",
    "be associated with",
    "embark on",
    "launch into",
    "occupy oneself",
    "take part",
    "throw oneself",
    "be a participant ",
    "be a party to",
    "go in for",
    "have a hand",
    "play a part",
    "play a role",
    "set about",
    "keep busy with",
    "be involved",
    "get involved",
    "compete",
    "perform",
    "contribute to",
    "be a participant",
    "engage in",
    "enter into",
    "join in",
    "sit in",
    "get in on the act",
    "be into",
    "have a hand in",
    "be party to",
    "sit in on",
    "have something to do with",
    "figure",
    "feature",
    "participate in",
    "share in",
    "get involved in",
    "partake in",
    "take part in",
    "play a part in",
    "be in on",
    "get in the act",
    "have a finger in",
    "be in the running",
    "be a competitor",
    "be a contestant",
    "help out",
    "support",
    "facilitate",
    "help",
    "assist",
    "aid",
    "chip in",
    "pitch in",
    "lend a hand",
    "associate oneself with",
    "go into",
    "associate with",
    "come in",
    "latch on",
    "tune in",
    "get in on",
    "come to the party",
    "take an interest in",
    "have to do with",
    "associate oneself",
    "be associated",
    "share in something",
    "go in for something",
    "throw oneself into something",
    "opt in",
    "be party to something",
    "have something to do with something",
    "be a party to something",
    "do",
    "exercise",
    "practise",
    "work as",
    "work at",
    "be employed as",
    "be employed at",
    "do for a living",
    "earn a living as",
    "have as an occupation",
    "have as a profession",
    "earn a living at",
    "try on",
    "check out",
    "wear",
    "appraise",
    "audition",
    "demonstrate",
    "experiment",
    "fit",
    "inspect",
    "practise",
    "probe",
    "prove",
    "sample",
    "scrutinise",
    "scrutinize",
    "taste",
    "test",
    "try out",
    "assess",
    "analyse",
    "check",
    "investigate",
    "evaluate",
    "examine",
    "assay",
    "trial",
    "try",
    "study",
    "verify",
    "put through its paces",
    "screen",
    "put to the test",
    "research",
    "give a tryout",
    "try on for size",
    "look into",
    "experimentalize",
    "experiment with",
    "analyze",
    "make a trial run",
    "scan",
    "carry out trials on",
    "shake down",
    "pilot",
    "explore",
    "put to trial",
    "turn over",
    "look at",
    "observe",
    "go over",
    "review",
    "vet",
    "field-test",
    "dig into",
    "road-test",
    "conduct experiments",
    "subject to an examination",
    "practice with",
    "carry out tests",
    "weigh",
    "fool with",
    "play around with",
    "carry out trials",
    "delve into",
    "do tests on",
    "conduct research",
    "test drive",
    "prospect",
    "futz around",
    "mess around",
    "diagnose",
    "see how it flies",
    "put something to the proof",
    "put something to the test",
    "substantiate",
    "see how wind blows",
    "stack up",
    "inquire",
    "run something up the flagpole",
    "send up a balloon",
    "put something through its paces",
    "run idea by someone",
    "run it up a flagpole",
    "prove out",
    "enquire",
    "validate",
    "quiz",
    "put someone to the test",
    "question",
    "match up",
    "confirm",
    "put someone through their paces",
    "provide",
    "prepare",
    "plan",
    "anticipate",
    "brace",
    "allow",
    "organise",
    "organize",
    "ready",
    "adapt",
    "adjust",
    "get ready",
    "make provision",
    "set up",
    "contrive",
    "guard",
    "practise",
    "forearm oneself",
    "lay the groundwork",
    "make provision for",
    "take measures",
    "take precautions",
    "take steps",
    "be prepared",
    "make arrangements",
    "make plans",
    "make preparations",
    "prime",
    "train",
    "warm up",
    "arrange things",
    "do the spadework",
    "gear oneself up",
    "face up to",
    "psych oneself up",
    "take the necessary steps",
    "fit oneself out",
    "rig oneself out",
    "kit oneself out",
    "arm oneself",
    "get everything set",
    "do the necessary",
    "go over",
    "analyse",
    "analyze",
    "consider",
    "discuss",
    "examine",
    "inspect",
    "investigate",
    "peruse",
    "practise",
    "read",
    "rehearse",
    "reiterate",
    "repeat",
    "review",
    "revise",
    "revisit",
    "scan",
    "skim",
    "study",
    "go into",
    "look at",
    "look into",
    "riffle through",
    "thumb through",
    "scrutinize",
    "look over",
    "survey",
    "check over",
    "scrutinise",
    "check out",
    "pore over",
    "check up on",
    "explore",
    "probe",
    "sift",
    "view",
    "evaluate",
    "audit",
    "delve into",
    "inquire about",
    "look-see",
    "case",
    "excogitate",
    "check up",
    "poke around",
    "go through",
    "run down",
    "look at carefully",
    "give something the once-over",
    "work at",
    "scrutinate",
    "read up on",
    "pry into",
    "reconnoiter",
    "search",
    "prospect",
    "scout",
    "probe into",
    "recce",
    "vet",
    "conduct an investigation into",
    "inquire into",
    "cross-examine",
    "subject to an examination",
    "eyeball",
    "nose around",
    "give the once over",
    "canvass",
    "take stock of",
    "inquisite",
    "reconnoitre",
    "check into",
    "scope out",
    "spy on",
    "make an observation of",
    "make a recce of",
    "perfect",
    "learn",
    "prepare",
    "refine",
    "polish",
    "check",
    "mug up on",
    "be tutored in",
    "polish up on",
    "take in",
    "bone up on",
    "be taught",
    "learn the ropes",
    "run through",
    "work on",
    "regulate",
    "reconsider",
    "give something a check-up",
    "strip down",
    "re-examine",
    "overhaul",
    "reexamine",
    "debug",
    "browse",
    "wade through",
    "skim through",
    "plough through",
    "bury oneself in",
    "devour",
    "scratch the surface",
    "con",
    "dip into",
    "flip through",
    "leaf through",
    "be absorbed in",
    "glance through",
    "look through",
    "browse through",
    "run your eye over",
    "cast an eye over",
    "follow",
    "flick through",
    "refer to",
    "research",
    "query",
    "work over",
    "enquire into",
    "conduct an enquiry into",
    "make inquiry",
    "brainstorm",
    "dig into",
    "weigh up",
    "sift the evidence concerning",
    "feel out",
    "listen in",
    "do research into",
    "wiretap",
    "put questions to",
    "sound out",
    "question",
    "size up",
    "ask questions of",
    "suss out",
    "bug",
    "dissect",
    "search into",
    "put to the test",
    "read into",
    "dive into",
    "stake out",
    "make enquiries about",
    "underseek",
    "search the evidence concerning",
    "tap",
    "test",
    "poke",
    "chew over",
    "mull over",
    "spy",
    "follow up",
    "make inquiries about",
    "try to get to the bottom of",
    "search for",
    "frisk",
    "brood over",
    "interrogate",
    "appraise",
    "deliberate on",
    "muckrake",
    "be all ears",
    "go in for",
    "enjoy",
    "follow",
    "like",
    "love",
    "participate in",
    "practise",
    "prefer",
    "take part in",
    "continue with",
    "keep on with",
    "devote oneself to",
    "work at",
    "engage in",
    "maintain",
    "apply oneself to",
    "stick at",
    "proceed in",
    "keep on",
    "go on with",
    "apply yourself to",
    "undertake",
    "proceed with",
    "adhere to",
    "pursue",
    "carry on",
    "go ahead with",
    "continue",
    "take further",
    "carry out",
    "see through",
    "wage",
    "proceed",
    "stick with",
    "prosecute",
    "perform",
    "be occupied in",
    "carry on with",
    "adhere",
    "hold to",
    "devote yourself to",
    "be engaged in",
    "apply oneself",
    "conduct",
    "tackle",
    "cultivate",
    "persist in",
    "ply",
    "persevere in",
    "take up",
    "direct",
    "manage",
    "discharge",
    "persist",
    "persevere",
    "fight",
    "follow up",
    "carry through",
    "follow through",
    "take",
    "study",
    "major in",
    "pursue",
    "take up",
    "concentrate on",
    "focus on",
    "learn",
    "specialise in",
    "specialize in",
    "do",
    "train in",
    "grasp",
    "master",
    "practise",
    "acquire a knowledge of",
    "apply oneself to",
    "be into",
    "be taught",
    "dedicate oneself to",
    "develop oneself in",
    "gain an understanding of",
    "have lessons in",
    "read",
    "read up on",
    "work at",
    "work in",
    "research",
    "do a degree in",
    "look up",
    "attain",
    "receive",
    "absorb",
    "acquire",
    "gain",
    "get",
    "imbibe",
    "comprehend",
    "digest",
    "assimilate",
    "observe",
    "calculate",
    "perceive",
    "note",
    "review",
    "understand",
    "enroll",
    "determine",
    "pick up",
    "swot",
    "prepare",
    "hit the books",
    "con",
    "get across",
    "know inside out",
    "acquire skill in",
    "glean",
    "get the point of",
    "apprentice",
    "peruse",
    "gather",
    "familiarize oneself with",
    "get clued up about",
    "familiarize yourself with",
    "become skilled at",
    "mug up",
    "become proficient in",
    "become expert in",
    "become competent in",
    "grind",
    "cram",
    "know backwards",
    "get the hang of",
    "get the knack of",
    "improve mind",
    "crack the books",
    "become versed",
    "minor in",
    "take course",
    "wade through",
    "pore over",
    "check",
    "soak up",
    "get down pat",
    "take in",
    "burn midnight oil",
    "drink in",
    "become able",
    "brush up on",
    "be trained",
    "watch",
    "enrol",
    "larn",
    "apprehend",
    "discern",
    "ascertain",
    "ingest",
    "drink",
    "sponge",
    "chalk up",
    "become versed in",
    "become familiar with",
    "suck up",
    "be informed of",
    "have knowledge of",
    "ponder",
    "contemplate",
    "consider",
    "think about",
    "devour",
    "analyse",
    "reflect on",
    "chew over",
    "weigh up",
    "analyze",
    "mull over",
    "meditate on",
    "meditate",
    "deliberate",
    "think over",
    "take on board",
    "appreciate",
    "process",
    "intuit",
    "follow",
    "cognize",
    "register",
    "catch",
    "savvy",
    "compass",
    "conceive",
    "integrate",
    "decipher",
    "dig",
    "decode",
    "realize",
    "sense",
    "recognize",
    "know",
    "seize",
    "see",
    "twig",
    "recognise",
    "realise",
    "absorb mentally",
    "latch onto",
    "soak in",
    "tumble to",
    "get into",
    "make out",
    "make of",
    "cotton on to",
    "cotton to",
    "catch on to",
    "swim",
    "bathe",
    "dip",
    "dive",
    "float",
    "plunge",
    "snorkel",
    "breast-stroke",
    "crawl",
    "dog-paddle",
    "freestyle",
    "go swimming",
    "high-dive",
    "move",
    "paddle",
    "practise",
    "race",
    "skinny-dip",
    "slip",
    "splash around",
    "stroke",
    "submerge",
    "wade",
    "tread water",
    "go wading",
    "take a dip",
    "go for a dip",
    "go for a swim",
    "scuba dive",
    "test",
    "trial",
    "experimental",
    "exploratory",
    "mock",
    "developmental",
    "pretend",
    "sample",
    "simulated",
    "pilot",
    "probationary",
    "provisional",
    "tentative",
    "confirmation",
    "corroboration",
    "elimination",
    "preliminary",
    "specimen",
    "fact-finding",
    "speculative",
    "probing",
    "empirical",
    "investigational",
    "introductory",
    "dummy",
    "model",
    "investigative",
    "testing",
    "searching",
    "initial",
    "balloon",
    "analytic",
    "explorative",
    "examining",
    "illustrative",
    "representative",
    "selected",
    "typifying",
    "typical",
    "observational",
    "objective",
    "existential",
    "untried",
    "hypothetical",
    "conjectural",
    "experiential",
    "prototype",
    "empiric",
    "untested",
    "trial-and-error",
    "temporary",
    "momentary",
    "trial and error",
    "preparatory",
    "under review",
    "laboratory",
    "primary",
    "beginning",
    "unproved",
    "unconcluded",
    "under the microscope",
    "on approval",
    "on the drawing board",
    "under probation",
    "first stage",
    "heuristic",
    "experience-based",
    "investigatory",
    "information-gathering",
    "research",
    "documentary",
    "evidential",
    "inquisitive",
    "penetrating",
    "piercing",
    "inquiring",
    "enquiring",
    "quizzical",
    "pointed",
    "deep",
    "thorough",
    "minute",
    "in-depth",
    "preseason",
    "preparatory",
    "warmup",
    "exhibition",
    "friendly",
    "training",
    "pre-season",
    "dummy",
    "fake",
    "false",
    "imitation",
    "mock",
    "artificial",
    "bogus",
    "simulated",
    "sham",
    "pretend",
    "feigned",
    "pretended",
    "ersatz",
    "factitious",
    "faux",
    "imitative",
    "make-believe",
    "man-made",
    "mimic",
    "phony",
    "phoney",
    "replica",
    "substitute",
    "synthetic",
    "trial",
    "reproduction",
    "counterfeit",
    "spurious",
    "pseudo",
    "forged",
    "fraudulent",
    "plastic",
    "manufactured",
    "unnatural",
    "affected",
    "unauthentic",
    "inauthentic",
    "faked",
    "so-called",
    "contrived",
    "fabricated",
    "cod",
    "assumed",
    "put-on",
    "facsimile",
    "unreal",
    "not genuine",
    "fictitious",
    "forced",
    "mechanical",
    "insincere",
    "dud",
    "invalid",
    "strained",
    "snide",
    "queer",
    "deceptive",
    "model",
    "made-up",
    "copied",
    "specious",
    "pseud",
    "pirated",
    "toy",
    "nonnatural",
    "worthless",
    "pirate",
    "misleading",
    "untrue",
    "invented",
    "copy",
    "knock-off",
    "quasi",
    "duplicate",
    "copycat",
    "trick",
    "representative",
    "trumped-up",
    "hokey",
    "supposititious",
    "fishy",
    "adulterine",
    "hoax",
    "illegal",
    "ungenuine",
    "framed",
    "bent",
    "phoney-baloney",
    "phony-baloney",
    "bootlegged",
    "repro",
    "miniature",
    "engineered",
    "mimetic",
    "echoic",
    "machine-made",
    "experimental",
    "counterfeited",
    "non-natural",
    "ostensible",
    "human-made",
    "falsified",
    "pinchbeck",
    "concocted",
    "falsie",
    "lookalike",
    "meretricious",
    "fallacious",
    "unqualified",
    "improvised",
    "pseudonymous",
    "adopted",
    "unoriginal",
    "crooked",
    "made",
    "makeshift",
    "constructed",
    "imaginary",
    "dishonest",
    "hyped up",
    "imagined",
    "apocryphal",
    "deceitful",
    "bum",
    "put on",
    "low-quality",
    "low-grade",
    "poor-quality",
    "shoddy",
    "inferior",
    "actorly",
    "quack",
    "dissembling",
    "unsatisfactory",
    "substandard",
    "adulterated",
    "quasi-",
    "mock-up",
    "fanciful",
    "mythical",
    "fantasy",
    "double-dealing",
    "gingerbread",
    "broken",
    "incorrect",
    "useless",
    "fancied",
    "fantasized",
    "dreamed-up",
    "dream",
    "fictive",
    "knock off",
    "fantastical",
    "chimerical",
    "fantasied",
    "visionary",
    "fabulous",
    "imaginal",
    "ideal",
    "chimeric",
    "fictional",
    "phantom",
    "notional",
    "mythic",
    "phantasmic",
    "fantastic",
    "phantasmal",
    "null",
    "not what it is cracked up to be",
    "Hollywood",
    "plant",
    "wrong",
    "suppositious",
    "brummagem",
    "pretentious",
    "delusory",
    "crock",
    "delusive",
    "play-play",
    "apish",
    "bad",
    "nugatory",
    "nonbinding",
    "void",
    "nonvalid",
    "inoperative",
    "null and void",
    "not binding",
    "uncollectible",
    "fantasised",
    "wont fly",
    "soft shell",
    "not kosher",
    "laboured",
    "labored",
    "hollow",
    "mannered",
    "stilted",
    "overdone",
    "stiff",
    "exaggerated",
    "unconvincing",
    "studied",
    "superficial",
    "wooden",
    "self-conscious",
    "overripe",
    "pseudo-",
    "purported",
    "professed",
    "alleged",
    "overworked",
    "supposed",
    "theatrical",
    "apparent",
    "seeming",
    "ham",
    "hammy",
    "avowed",
    "virtual",
    "masked",
    "concealed",
    "imitated",
    "unspontaneous",
    "would-be",
    "covered",
    "constrained",
    "staged",
    "rehearsed",
    "surface",
    "stagy",
    "overblown",
    "manmade",
    "derivative",
    "non-existent",
    "chemical",
    "cast",
    "elaborate",
    "planned",
    "wannabe",
    "self-styled",
    "nominal",
    "ostensive",
    "semi-",
    "posed",
    "made up",
    "mealymouthed",
    "unsubstantiated",
    "baseless",
    "groundless",
    "unfounded",
    "unproven",
    "glib",
    "deceiving",
    "near",
    "reported",
    "posey",
    "campy",
    "not real",
    "not legit",
    "awkward",
    "conceited",
    "playacting",
    "melodramatic",
    "affectated",
    "fraud",
    "manipulated",
    "far-fetched",
    "fixed",
    "recherche",
    "voulu",
    "as it were",
    "hypocritical",
    "without foundation",
    "rigid",
    "inflexible",
    "grudging",
    "bound",
    "binding",
    "conscripted",
    "slave",
    "begrudging",
    "stringent",
    "coercive",
    "forcible",
    "overly planned",
    "bluffing",
    "shammed",
    "lying",
    "impostrous",
    "in name only",
    "charlatan",
    "cheating",
    "dissimulated",
    "imposturous",
    "to all intents and purposes",
    "wreck",
    "wired",
    "put",
    "unglued",
    "uptight",
    "tight",
    "choked",
    "taut",
    "farfetched",
    "abnormal",
    "unusual",
    "strange",
    "odd",
    "extraordinary",
    "cooked up",
    "in a state",
    "hard put",
    "nervous wreck",
    "strung out",
    "at end of rope",
    "irregular",
    "freakish",
    "anomalous",
    "bizarre",
    "aberrant",
    "atypical",
    "uncommon",
    "untypical",
    "unorthodox",
    "weird",
    "freak",
    "peculiar",
    "perverted",
    "divergent",
    "uncanny",
    "deviant",
    "perverse",
    "aberrational",
    "devious",
    "exceptional",
    "supernatural",
    "non-typical",
    "outlandish",
    "deviate",
    "camouflaged",
    "unrecognizable",
    "unaccountable",
    "preternatural",
    "hidden",
    "covert",
    "sly",
    "incognito",
    "inexplicable",
    "surprising",
    "outrageous",
    "contrary",
    "unconforming",
    "incredible",
    "freaky",
    "paranormal",
    "eerie",
    "preposterous",
    "undercover",
    "furtive",
    "back-alley",
    "underhand",
    "sneaky",
    "masquerading",
    "disguised",
    "changed",
    "veiled",
    "unrecognisable",
    "incog",
    "cloaked",
    "in disguise",
    "sailing under false colours",
    "under cover"
  ])
];

const out = [
  ...CODE.flatMap(x => TRAIN.map(y => `${x}${y}`)),
  ...CODE.flatMap(x => TRAIN.map(y => `${y}${x}`)),
  ...CODE.flatMap(x => MOBILE.map(y => `${x}${y}`)),
  ...CODE.flatMap(x => MOBILE.map(y => `${y}${x}`)),
  ...TRAIN.flatMap(x => MOBILE.map(y => `${x}${y}`)),
  ...TRAIN.flatMap(x => MOBILE.map(y => `${y}${x}`))
]
  .map(x => `${x}.com`)
  .sort((a, b) => a.length - b.length);
require('fs').writeFileSync("./big.json", JSON.stringify(out), "utf8");
// console.log(out);
