# Path to your oh-my-zsh installation.
export ZSH=/home/gcg/.oh-my-zsh

ZSH_THEME="agnoster"
HIST_STAMPS="yyyy-mm-dd"
plugins=(git jsontools sudo cloudapp)

export PATH="/home/gcg/.gem/ruby/2.3.0/bin:/opt/android-sdk-linux/tools:/opt/android-sdk-linux/platform-tools:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
export PATH="$PATH:./node_modules/.bin:../node_modules/.bin:../../node_modules/.bin:../../../node_modules/.bin:../../../../node_modules/.bin"
export PATH="$PATH:$(yarn global bin 2>/dev/null)"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8
#
alias vincenza='ssh -o PubKeyAuthentication=no -p 2222 vincenza@maisonvincenza.com.br'
export VISUAL=nvim
export EDITOR="$VISUAL"
alias webcam='guvcview'
alias griom='git rebase -i origin/master'
alias n='nvim'
nag () { n "+/\c$*" `ag -l "$*"` }
nf () { n `find -name "$*" -not -path "./node_modules/*"` }
nlint() { n `eslint --cache -f ./node_modules/eslint-formatter-list .` }
alias f='ag -g'
alias w='watch -n 0.5'
alias v='viewnior'
alias c='xclip -selection clipboard'
alias wr='nmcli r w off&&nmcli r w on'
alias ww='watch nmcli d w'
alias performance='for i in `ls -d /sys/devices/system/cpu/cpu*|grep -v cpufreq|grep -v cpuidle`; do echo performance | sudo tee --append $i/cpufreq/scaling_governor >/dev/null; done'
alias powersave='for i in `ls -d /sys/devices/system/cpu/cpu*|grep -v cpufreq|grep -v cpuidle`; do sudo echo powersave  | sudo tee --append $i/cpufreq/scaling_governor >/dev/null; done; xbacklight -set 7'
alias hibernate='echo disk | sudo tee /sys/power/state'
alias suspend='echo mem | sudo tee /sys/power/state'
alias wf='chromium --app="https://workflowy.com" --enable-apps --enable-extension-apps'

alias curlpost='curl -v -H "Content-Type: application/json" -d -'
gif() { ffmpeg -i $1 $1.gif }
speedup() { ffmpeg -i $1 -filter_complex "[0:v]setpts=0.8*PTS[v]" -map "[v]" fast-$1 }
speedupx() { ffmpeg -i $1 -filter_complex "[0:v]setpts=$2*PTS[v]" -map "[v]" fast-$1 }
speedupa() { ffmpeg -i $1 -filter_complex "[0:v]setpts=0.8*PTS[v];[0:a]atempo=1.25[a]" -map "[v]" -map "[a]" fast-$1 }
reload() { source ~/.zshrc }
hash -d -- i=/home/gcg/inv

export TERM=screen-256color

eval $(dircolors ~/.dircolors)

eval $(keychain --eval --quiet id_rsa)

if [[ $TERM == xterm-termite ]]; then
  . /etc/profile.d/vte.sh
  __vte_osc7
fi

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /home/gcg/.config/yarn/global/node_modules/tabtab/.completions/serverless.zsh ]] && . /home/gcg/.config/yarn/global/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /home/gcg/.config/yarn/global/node_modules/tabtab/.completions/sls.zsh ]] && . /home/gcg/.config/yarn/global/node_modules/tabtab/.completions/sls.zsh
